---
# tasks file for percona tools related tasks
- name: install percona repository
  shell: rpm -ivh --force http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm

- name: install percona-toolkit on target host
  yum: name=percona-toolkit state=installed

- name: install pt-log-player
  copy: src=pt-log-player dest=/usr/bin/pt-log-player owner=root group=root mode=0755

- name: configure the pt-log-player config file
  template: src=pt-log-player.conf.j2 dest=/root/.pt-log-player.conf owner=root group=root mode=0600

- name: configure the pt-log-player config file on compare host
  template: src=pt-log-player.conf.j2 dest=/root/.pt-log-player.conf owner=root group=root mode=0600
  delegate_to: "{{ mysql_compare_host }}"

- name: configure the pt-upgrade config file
  template: src=pt-upgrade.conf.j2 dest=/root/.pt-upgrade.conf owner=root group=root mode=0600

- name: configure the pt-upgrade config file on compare host
  template: src=pt-upgrade.conf.j2 dest=/root/.pt-upgrade.conf owner=root group=root mode=0600
  delegate_to: "{{ mysql_compare_host }}"