---
# tasks file for installing tools needed to run the tests
- name: install required tools on target host
  yum: name={{ item }} state=installed
  with_items:
    - nc
  register: tools_install

- name: install required tools on master host
  yum: name={{ item }} state=installed
  with_items:
    - nc
    - tcpdump
  delegate_to: "{{ mysql_master_host }}"
  register: tools_install_master

- name: install required tools on localhost
  copy: src=pt-log-player dest=/usr/bin/pt-log-player owner=root group=root mode=0755
  delegate_to: 127.0.0.1