---
- name: >
    RedHat | set_fact
      mysql_supported_os: True
  set_fact:
    mysql_supported_os: True

- name: RedHat | create directory to store rpm
  file: path={{ rpm_download_dir}} state=directory

- name: RedHat | download mysql rpms
  get_url: url={{ mysql_download_url }}/{{ item }} dest={{ rpm_download_dir }}/{{ item }}
  with_items: mysql_rpms

- name: RedHat | clean old upgrade markers
  command: rm -f /var/lib/mysql/RPM_UPGRADE_MARKER

- name: RedHat | install mysql rpms
  command: rpm -ivh {{ rpm_download_dir }}/*.rpm 
  register: mysql_install

- name: RedHat | empty the directories
  shell: rm -rf {{ mysql_datadir }}/* {{ mysql_logdir }}/* {{ mysql_tmpdir }}/*

- name: RedHat | setup directory permissions
  file: path={{ item }} state=directory owner=mysql group=mysql mode=0755
  with_items:
    - "{{ mysql_datadir }}"
    - "{{ mysql_logdir }}"
    - "{{ mysql_tmpdir }}"

- name: RedHat | configure the service
  template: src=RedHat-my.cnf.j2 dest=/etc/my.cnf owner=root group=root mode=0644

- name: RedHat | install mysql system databases
  command: mysql_install_db --user={{ mysql_user }} --datadir={{ mysql_datadir }}

- name: backup_and_restore | stop mysql service
  service: name=mysql state=started

- name: RedHat | install additional packages
  yum: name=MySQL-python state=installed
